config/routes.rb
Whitbygas::Application.routes.draw do

root to: 'pages#home'

  match '/home', to:  'pages#home'
  match 'contact' =>  'contact#new', :as => 'contact', :via => :get
  match 'contact' =>  'contact#create', :as => 'contact', :via => :post

  match '/about', to:  'pages#about'

  match '/services', to:  'pages#services'

  match '/products', to:  'pages#products'
  match '/portfolio', to:  'pages#port'

end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :body

  validates :name, :email, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])

    if @message.valid?
      EnquiryMailer.new_message(@message).deliver
      redirect_to(contact_path, :notice => "Message was successfully sent.")
    else
      flash.now.alert = "Please fill all fields."
      render :new
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def view
  end

  def product
  end

  def services
  end

  def portfollio
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  # returns the full page title
  def full_title(page_title)
    base_title = " whitbyplumbing.co.uk Whitby Plumbing "
    if page_title.empty?
     base_title
    else
     "#{base_title} - #{page_title}"
    end
  end

end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contact/new.html.erb
         <div class="row">

                <div class="span3">
                    <h2>Our location</h2>
                    <h3>Address:</h3>
                    <p>18 Mayfield Road<br />Whitby<br />North Yorkshire<br />YO211LX</p>	
                    <div style="width:200px;height:200px"><iframe width="200" height="200" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.co.uk/maps?q=whitby+uk&amp;ie=UTF8&amp;hq=&amp;hnear=Whitby,+North+Yorkshire,+United+Kingdom&amp;gl=uk&amp;t=m&amp;ll=54.486295,-0.613346&amp;spn=0.019944,0.034504&amp;z=13&amp;iwloc=A&amp;output=embed"></iframe><br /><small><a href="https://maps.google.co.uk/maps?q=whitby+uk&amp;ie=UTF8&amp;hq=&amp;hnear=Whitby,+North+Yorkshire,+United+Kingdom&amp;gl=uk&amp;t=m&amp;ll=54.486295,-0.613346&amp;spn=0.019944,0.034504&amp;z=13&amp;iwloc=A&amp;source=embed" style="color:#0000FF;text-align:left">View Larger Map</a></small>
                    </td><td align="right"><small></small></td></tr></table></div><br /><br />
                    <h3>Telephone:</h3>
                    <p>Tel:01947 602375<br />Mob: 07870582024</p>	
                </div>
                <div class="span9">
                    <div class="page-header">
                        <h1>Contact Us</h1>
                    </div>

                    <% flash.each do |name, message| %>
                      <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
                      <a class="close" data-dismiss="alert">x</a>
                        <%= message  %>
                      </div>
                   <% end %>


                    <!-- Headings & Paragraph Copy -->
		   <p><h5>For advice or to arrange a service, repair or quote. Please call Trevor or drop us an email using the contact form below.</h5></p><br />

		   <div class="row">
                     <div class="span6">
                        <fieldset>
                          <%= simple_form_for @message, :html => {:class => "form-horizontal"}, :url => contact_path do |form| %>
                          <%= form.input :name, :label => 'First Name: ', :placeholder => 'Your first name.', :input_html => {:class => "span6"}  %>
                          <%= form.input :email, :label => 'Email address: ', :placeholder => 'your email address.', :input_html => {:class => "span6"} %>
                          <%= form.input :body , :label => 'Enquiry: ', :as => :text, :placeholder => 'What you would like to contact us about.', :input_html => {:cols => 50, :rows =>5, :class => 'input-xlarge-focused span6 '} %>
                          </br>
                          <%= form.button :submit, :label => 'Send Enquiry',  :class =>  "btn btn-primary pull-right"  %>
                          <% end %>
                        </fieldset>
                      </div>
                    </div><!-- /row -->
                </div>
`

app/views/layouts/_aboutus.html.erb
<div class="row">
                <div class="span12 page-title-container">
                <%= link_to image_tag("page-about.jpg", alt: "Fireplace"), '#' %>

                    <div class="inner-page-title fixed">
                        <h2>About</h2>
                        <p> TA Freeman Plumbing and Heating Engineers. Est 1980</p>
                    </div>
                </div>
</div>
<hr>
<div class="row">
                <div class="span12">
                    <div class="span12 single">
                        <p>
 If you are looking for a reliable and skilled plumber with a focus on customer service give us a call today. Please browse our website for information on all of our services                        
                       </p>
                       <p>
As well as our domestic services at TA Freeman Plumbing and Heating we can also carry out work on commercial heating and plumbing systems. As with our domestic customers we know that a business cannot afford long disruptions caused by loss of heating or water supplies so we will always turn up when we say we will and will work quickly to resolve any problems</p>
                        <blockquote>
                            <p>
We can also undertake contract maintenance work and regular servicing to try to prevent problems happening in the first place.
</p>
                            <small>Someone famous</small>
                        </blockquote>
                        <div class="row">
                            <div class="span4">


                                Etiam pellentesque, magna eget lobortis placerat, leo leo consequat ante, non iaculis turpis augue ac ligula. Nunc blandit tincidunt consequat.
                                <ul>
                                  <li>Annual Boiler Services</li>
                                  <li>Gas Boiler Installation</li>
                                  <li>Combi Boiler Repairs</li>
                                  <li>Gas Fire Repairs</li>
                                  <li>Plumbing Services</li>
                                  <li>Gas Boiler Insurance Cover</li>
                                  <li>Landlord Safety Certificates</li>
                                  <li>All types of plumbing work from full bathroom suitesto leaking taps</li>
                                  <li>Sell and Install Gas Fires and Surrounds</li>
                                </ul>

                            </div>
                            <div class="span2">
                                <img src="img/service-1.jpg"><br><br>
                                <p> Etiam pellentesque, magna eget lobortis placerat, leo leo consequat ante</p>
                            </div>
                            <div class="span2">
                                <img src="img/service-2.jpg"><br><br>
                                <p> Etiam pellentesque, magna eget lobortis placerat, leo leo consequat ante</p>
                            </div>
                        </div>
                        <hr>
                        <p>

Whether you are looking for a new boiler or central heating system to be installed or alternatively are looking to increase the efficiency of your current system by carrying out, for example a powerflush, then our engineers at TA Freeman have the necessary knowledge, experience and accreditations to do this.
                        </p>

                    </div>
                </div>
            </div>

app/views/layouts/_footer.html.erb
  <footer>
                <hr/>
                <div class="row">
                    <div class="span3">
                        <h4>&COPY; 2012 T A Freeman</h4><br/>

                        All right are reserved.<br/>
                        <a href="#">Terms of Service</a> | <a href="#">Privacy Policy</a>
                    </div>
                    <div class="span3">
                        <h4>Contact Info</h4>
                        <br />
                        <p>
                            T A Freeman.<br/>
                            Plumbing and Heating Engineers<br/>
                            18 Mayfield Road<br/>
                            Whitby<br/>
                            North Yorkskhire<br/>
                            YO21 1LX <br/>
                            Tel: 01947 602375
                        </p>
                    </div>

                    <div class="span3">
                        <h4>Quick Navigation</h4>
                        <br/>
                        <ul>
                            <li><%= link_to "Home", root_path %></li>
                            <li><%= link_to "About", about_path %></li>
                            <li><%= link_to "Services", services_path %></li>
                            <li><%= link_to "Products", products_path %></li>
                            <li><%= link_to "Portfolio", portfolio_path %></li>
                            <li><%= link_to "Contact Us", contact_path %></li>
                        </ul>
                    </div>
                    <div class="span3">
                        <h4>Connect with us</h4>
                        <br/>
                        <%= link_to image_tag("twitter.png", alt: "twitter"), 'http://www.twitter.com/@whitbyplumber' %>
                        <a href="http://twitter.com/@whitbyplumber">Twitter</a>
                        <br/><br />
                        <%= link_to image_tag("facebook.png", alt: "facebook"), 'http://www.facebook.com/pages/TA-freeman-plumbing-and-heating-engineers/407354076015352' %>
                        <a href="http://www.facebook.com/pages/TA-freeman-plumbing-and-heating-engineers/407354076015352">Facebook</a>
                    </div>

                </div>
  </footer>

app/views/layouts/_header.html.erb
<header class="header">
     <div class="row">
                <div class="span4 logo">
                    <a href="<%= root_path %>">
                            <%= link_to image_tag("TAFreeman.png", alt: "gassafe"), 'http://www.gassaferegister.co.uk/' %> 
                    </a>
                </div>
     </div>
     <div class="row">
                <div class="span4 logo">
                    <a href="<%= root_path %>">
                        <h1 class="logo-title">&nbsp</h1>
                    </a>
                    <span class="slogan"> <strong> Plumbing and Heating Engineers - Whitby</strong></span>
                </div>
                <div class="offset2 span6">
                            <h4><small>For all  information call Trevor on: <strong>07870582024 </strong> or<strong> 01947602375</strong></small></h4>
                            <div class="offset4 span2">
                            <%= link_to image_tag("gassafe.png", alt: "gassafe"), 'http://www.gassaferegister.co.uk/' %> 
                            <%= link_to image_tag("corgi.png", alt: "corgi"), 'http://www.gassaferegister.co.uk/' %> 
                            </div>
                </div>
    </div>
<!-- Start Navigation -->
            <div class="row">
                <div class="span12">
                    <div class="navbar">
                        <div class="navbar-inner">
                            <div class="container" style="width: auto;">
                                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </a>
                                <div class="nav-collapse">
                                    <ul class="nav pull-right">
                                        <li><%= link_to "Home", root_path %></li>
                                        <li><%= link_to "About", about_path %></li>
                                        <li><%= link_to "Services", services_path %></li>
                                        <li><%= link_to "Products", products_path %></li>
                                        <li><%= link_to "Portfolio", portfolio_path %></li>
                                        <li><%= link_to "Contact", contact_path %></li>

                                    </ul>

                                </div>
                            </div>
                        </div>
                    </div>
                    <hr/>
                </div>
            </div>
<!-- End Navigation -->
</header>

app/views/layouts/_home.html.erb
<div class="row">
                <div class="span12">
                    <div id="myCarousel" class="carousel slide">
                        <div class="carousel-inner">
                            <div class="item">
				<%= link_to image_tag("1.jpg", alt: "Fireplace"), '#' %>
                                <img alt="Gas fireplace installer" src="1.jpg" />
                                <div class="carousel-caption">
                                    <h4>Heating installations</h4>
                                    <p>Boiler and Central heating fitting. Underfloor heating. </p>
                                </div>

                            </div>

                            <div class="item active">
				<%= link_to image_tag("3.jpg", alt: "Heating Engineer"), '#' %>
                                <div class="carousel-caption">
                                    <h4>Plumbing and Gas fitting</h4>
                                    <p> Bathrooms, Wetrooms. We give the complete service from start to finish. </p>
                                </div>
                            </div>

                            <div class="item">
				<%= link_to image_tag("2.jpg", alt: "Bathroom"), '#' %>
                                <div class="carousel-caption">
                                    <h4>Fire installs </h4>
                                    <p>Gas fireplaces. Gas safe registered fitters. </p>
                                        </p>
                                </div>
                            </div>

                            <div class="item">
				<%= link_to image_tag("4.png", alt: "Plumber"), '#' %>
                                <div class="carousel-caption">
                                    <h4>Bathroom Plumbing</h4>
                                    <p> Bathroom design,planning,fit. Total solution. </p>
                                </div>
                            </div>

                            <div class="item">
				<%= link_to image_tag("5.jpg", alt: "Heating"), '#' %>
                                <div class="carousel-caption">
                                    <h4>Central Heating - by experts</h4>
                                    <p> Central Heating design and fitting. Over 20 years experience. </p>
                                </div>
                            </div>
                        </div>
                        <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>
                        <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a>
                    </div>
                </div>
            </div>
<div class="row">
                <div class="span3">
                    <h3>What We Do</h3>
                    <p>
                        We are plumbing and heating engineers -  Serving Whitby and local area. 

                        Our aim is to give you the total service from the design stage  to planning and installation.

                        We can also repair service your existing gas appliances and advise on upgrades. &nbsp; <%= link_to "More.", services_path %>
                    </p>
                </div>
                <div class="span9">
                    <div class="row">
                        <div class="span9">
                            <h3>Services</h3> 
                           <%= link_to "View all our services", services_path, class: "pull-right" %>
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="span9">
                            <ul class="thumbnails">
                                <li class="span3">
                                     <div class="service-box">
                                        <div class="caption">
                                            <a href="service_detail.html"><h4>Wet Rooms</h4></a>
                                            <p>
                                               Expert Wetroom installations. 
                                            </p>
                                        </div>
                                        <%= link_to image_tag("wetroom.jpg", alt: "wetroom"), '#' %>

                                    </div>
                                </li>       
                                <li class="span3">
                                 <div class="service-box">
                                        <div class="caption">
                                            <a href="service_detail.html"><h4>Bathroom fitting</h4></a>
                                            <p>
                                               Full bathroom design plan and fit service. 
                                            </p>
                                        </div>
                                        <%= link_to image_tag("bathroom.jpg", alt: "bathroom"), '#' %>
                                    </div>
                                </li>       
                                <li class="span3">
                                   <div class="service-box">
                                        <div class="caption">
                                            <a href="service_detail.html"><h4>Boiler installs / Service</h4></a>
                                            <p>
                                               Boiler and Central heating installations. 
                                            </p>
                                        </div>
                                        <%= link_to image_tag("boiler.jpg", alt: "boiler"), '#' %>
                                    </div>


                                </li>        

                            </ul>
                        </div>
                    </div>

                </div>
                <div class="span12">
                </div>
            </div>
<div class="row">
                <div class="span3">
                    <h3>About Us</h3>
                    <p>
                        Established over 20 years ago TA Freeman has being serving the Whitby Area for many areas.  
                        Corgi registered and Gas Safe registered engineers.

                    </p>
                    <p>
                        Installation,Service and Repairs.
                        &nbsp;<a href="about.html">more detail</a>
                    </p>
                </div>
                <div class="span9">
                    <div class="row">
                        <div class="span3">
                                    <blockquote>
                                        <p>What we've been working on.</p>
                                    </blockquote>
                            <ul id="news-box"> 
                                <li class="first"> 
                                    <a href="portfolio.html">Install of 14 Wetrooms at Peregrine House</a> <br> 
                                    <span>Oct 2012</span> 
                                </li> 
                                <li> <a href="portfolio.html">Hadleys Accommodation</a> <br> 
                                    <span>Jan 2013 </span> 
                                </li> 

                            </ul>
                        </div>
                        <div class="span6">

                            <div class="row">
                                <div class="span6">
                                    <blockquote>
                                        <p>"Execellent service from Start to Finish, Thoroughly recommended"</p>
                                        <small> JD Roach Builders - Peregrine House. Oct 2012</small>
                                    </blockquote>

                                    <blockquote>
                                        <p>"Brilliant work"</p>
                                        <small>Hadleys Accommodation. Dec 2012</small>
                                    </blockquote>
                                </div>
                            </div>
                            <div class="row">
                                <div class="span6">
                                    <h3>Just some of the products we use.</h3><br>
                                    <ul class="thumbnails">
                                        <li class="span2">
                                            <div class="service-box">
						<%= link_to image_tag("baxi.jpg", alt: "baxi" ), 'http://www.baxi.co.uk/about/products.htm'%>
                                            </div>
                                        </li>
                                        <li class="span2">
                                            <div class="service-box">
                                               <%= link_to image_tag("gazco.jpg", alt: "gazco"), 'http://www.stovax.com/' %> 
                                            </div>
                                        </li>
                                        <li class="span2">
                                            <div class="service-box">
                                                <%= link_to image_tag("vaillant.jpg", alt: "valliant"), 'http://www.vaillant.co.uk/homeowner' %>
                                            </div>
                                        </li>        

                                    </ul>
                                </div>
                            </div>


                        </div>
                    </div>

                </div>

            </div>

app/views/layouts/_port.html.erb
<h3>Recent work we have completed</h3>
<div class="row">
                <div class="span12 page-title-container">
                     <%= link_to image_tag("4.png", alt: "Bathroom design picture"), '#' %>

                     <div class="inner-page-title fixed">
                            <br/>
                            <br/>
                            <br/>
                        <h2>Portfolio</h2>
                        <p>Here is the detail on some of our work.</p>
                    </div>
                </div>
            </div>
            <hr/>
            <div class="row">
                <div class="span3">

                </div>

                <div class="span9">

                    <div class="row">
                        <div class="span3">
                           <%= link_to image_tag("moonbath.png", alt: "Moon and sixpence bathroom"), '#' %>
                        </div>
                        <div class="span3">
                           <%= link_to image_tag("moonshower.png", alt: "Moon and sixpence bathroom"), '#' %>
                        </div>
                        <div class="span3">
                            <a href="http://www.moon-and-sixpence.co.uk"><h4>The Moon and Sixpence</h4></a>
                            <p>
                               Design supply and fit of accomadation bathrooms for the renowned seafront bar and brasserie in Whitby.  
                            </p>
                        </div>
                        <div class="span9">
                            <br/>
                            <blockquote>
                              <p>
                                 &quot I'd reccommend Trevor without  hesitation. He did an excellent job for us.&quot - Dave Ellis - Moon and Sixpence - Whitby.
                              </p>
                           </blockquote>
                        </div>	 
                    </div>
                    <hr>

                    <div class="row">
                        <div class="span3">
                           <%= link_to image_tag("peregrine-house.jpg", alt: "peregrinehouse plumbing"), {:class => '.img-rounded'} %>
                           <%= link_to image_tag("nhbc.png", alt: "national homebuilders"), {:class => '.img-rounded'} %>
                           <%= link_to image_tag("fmb.png", alt: "Federation Master Builders"), {:class => '.img-rounded'} %>
                        </div>
                        <div class="span6">
                            <a href="http://peregrinehouse.com"><h4>Peregine House</h4></a>
                            <p>
                                In association with JD Roach Builders - Fitting of wetrooms and underfloor heating for 14 rooms in the Pereginehouse residential care home.
                            </p>
                            <blockquote>
                              <p>
                                 TA Freeman and JD Roach builders - Peregine House - Whitby. Oct 2012
                              </p>
                           </blockquote>
                            <br/>
                        </div>	 
                    </div>
                    <hr>
                    <div class="row">
                        <div class="span3">
                            <a href="http://www.hadleysfishrestaurant.com"><h4>Hadleys Delux Accommodation - Whitby</h4></a>
                            <p>
                                Fitting of on-suite and heating systems for 5 rooms in Hadleys delux holiday accommodation in Whitby. - Jan 2013 
                            </p>
                            <br/>
                        </div>	 
                        <div class="span3">
                           <%= link_to image_tag("hadleys1.png", alt: "Hadleys Whitby"), {:class => '.img-rounded'} %>
                        </div>
                        <div class="span3">
                           <%= link_to image_tag("hadleys2.png", alt: "Hadleys Whitby"), {:class => '.img-rounded'} %>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="span9">
                            <a href="http://www.the-marine-hotel.co.uk/"><h4>The Marine Hotel - Whitby</h4></a>
                            <p>
                                Fitting of on-suite and heating systems for 4 rooms in the Marine Bar - Hotel Whitby.
                            </p>
                            <br/>
                        </div>	 
                    </div>
                        <div class="span3">
                           <%= link_to image_tag("marine1.png", alt: "Whitbyplumbing Marine Whitby"), {:class => '.img-rounded'} %>
                        </div>
                        <div class="span3">
                           <%= link_to image_tag("marine3.png", alt: "Marine Whitbyi ~whitby Plumbing"), {:class => '.img-rounded'} %>
                        </div>
                    </div>
                </div>

app/views/layouts/_products.html.erb
<div class="row">
  <div class="span12"> 
    <h4>We install and service products from all major brands, including the manufactures shown below.</h4>
 </div>
</div>

<div class="row">
  <div class="span12"> 
  <br>
 </div>
</div>

<div class="row">
        <div class="span4">
         <%= link_to image_tag("baxi.jpg", alt: "baxi" ), 'http://www.baxi.co.uk/about/products.htm'%>
        </div><!-- /.span4 -->

        <div class="span4">
        <%= link_to image_tag("bosch.jpg", alt: "bosch"), 'http://www.woreester-bosch.co.uk/homeowner' %>
        </div class="span4">
        <div>
          <%= link_to image_tag("vaillant.jpg", alt: "valliant"), 'http://www.vaillant.co.uk/homeowner' %>
        </div><!-- /.span4 -->
</div>

<div class="row">
        <div class="span3">
          <%= link_to image_tag("idealstandard.png", alt: "idealstandard"), 'http://www.idealstandard.co.uk/' %>
        </div><!-- /.span3-->
        <div class="span3">
          <%= link_to image_tag("gazco.jpg", alt: "gazco"), 'http://www.stovax.com/' %>
        </div><!-- /.span3 -->
        <div class="span3">
          <%= link_to image_tag("uponor.png", alt: "uponor"), 'http://www.uponor.co.uk/' %>
        </div><!-- /.span3 -->
        <div class="span3">
          <%= link_to image_tag("idealboilers.jpg", alt: "idealboilers"), 'http://www.idealheating.com/' %>
        </div><!-- /.span3 -->
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/pages/about.html.erb
<% provide(:title, 'About Us') %>
<%= render ('layouts/aboutus') %>

app/views/pages/home.html.erb
<% provide(:title, 'Home') %>
<%= render ('layouts/home') %> 

app/views/pages/port.html.erb
<% provide(:title, 'Portfolio') %>
<%= render ('layouts/port') %> 

app/views/pages/portfollio.html.erb
<h1>Pages#portfollio</h1>
<p>Find me in app/views/pages/portfollio.html.erb</p>

app/views/pages/products.html.erb
<% provide(:title, 'Products') %>
<%= render ('layouts/products') %> 

app/views/pages/services.html.erb
<% provide(:title, 'Services') %>
<%= render ('layouts/services') %> 

app/views/pages/view.html.erb
<h1>Pages#view</h1>
<p>Find me in app/views/pages/view.html.erb</p>